[2025-01-24T23:03:16.306+0000] {processor.py:186} INFO - Started process (PID=53) to work on /opt/airflow/dags/finalassignment/tolldata/ETL_dag.py
[2025-01-24T23:03:16.310+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/finalassignment/tolldata/ETL_dag.py for tasks to queue
[2025-01-24T23:03:16.316+0000] {logging_mixin.py:190} INFO - [2025-01-24T23:03:16.315+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/finalassignment/tolldata/ETL_dag.py
[2025-01-24T23:03:16.333+0000] {logging_mixin.py:190} INFO - [2025-01-24T23:03:16.328+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/finalassignment/tolldata/ETL_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/finalassignment/tolldata/ETL_dag.py", line 9, in <module>
    csv_file = os.path.join(base_path, "vehicle-data.csv")
                            ^^^^^^^^^
NameError: name 'base_path' is not defined
[2025-01-24T23:03:16.335+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/finalassignment/tolldata/ETL_dag.py
[2025-01-24T23:03:16.387+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/finalassignment/tolldata/ETL_dag.py took 0.090 seconds
[2025-01-24T23:03:47.366+0000] {processor.py:186} INFO - Started process (PID=117) to work on /opt/airflow/dags/finalassignment/tolldata/ETL_dag.py
[2025-01-24T23:03:47.368+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/finalassignment/tolldata/ETL_dag.py for tasks to queue
[2025-01-24T23:03:47.371+0000] {logging_mixin.py:190} INFO - [2025-01-24T23:03:47.371+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/finalassignment/tolldata/ETL_dag.py
[2025-01-24T23:03:47.378+0000] {logging_mixin.py:190} INFO - [2025-01-24T23:03:47.376+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/finalassignment/tolldata/ETL_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/finalassignment/tolldata/ETL_dag.py", line 9, in <module>
    csv_file = os.path.join(base_path, "vehicle-data.csv")
                            ^^^^^^^^^
NameError: name 'base_path' is not defined
[2025-01-24T23:03:47.379+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/finalassignment/tolldata/ETL_dag.py
[2025-01-24T23:03:47.405+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/finalassignment/tolldata/ETL_dag.py took 0.046 seconds
[2025-01-24T23:04:18.081+0000] {processor.py:186} INFO - Started process (PID=180) to work on /opt/airflow/dags/finalassignment/tolldata/ETL_dag.py
[2025-01-24T23:04:18.083+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/finalassignment/tolldata/ETL_dag.py for tasks to queue
[2025-01-24T23:04:18.086+0000] {logging_mixin.py:190} INFO - [2025-01-24T23:04:18.085+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/finalassignment/tolldata/ETL_dag.py
[2025-01-24T23:04:18.095+0000] {logging_mixin.py:190} INFO - [2025-01-24T23:04:18.090+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/finalassignment/tolldata/ETL_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/finalassignment/tolldata/ETL_dag.py", line 9, in <module>
    csv_file = os.path.join(base_path, "vehicle-data.csv")
                            ^^^^^^^^^
NameError: name 'base_path' is not defined
[2025-01-24T23:04:18.096+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/finalassignment/tolldata/ETL_dag.py
[2025-01-24T23:04:18.118+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/finalassignment/tolldata/ETL_dag.py took 0.042 seconds
[2025-01-24T23:04:48.424+0000] {processor.py:186} INFO - Started process (PID=244) to work on /opt/airflow/dags/finalassignment/tolldata/ETL_dag.py
[2025-01-24T23:04:48.426+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/finalassignment/tolldata/ETL_dag.py for tasks to queue
[2025-01-24T23:04:48.428+0000] {logging_mixin.py:190} INFO - [2025-01-24T23:04:48.428+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/finalassignment/tolldata/ETL_dag.py
[2025-01-24T23:04:48.441+0000] {logging_mixin.py:190} INFO - [2025-01-24T23:04:48.437+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/finalassignment/tolldata/ETL_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/finalassignment/tolldata/ETL_dag.py", line 9, in <module>
    csv_file = os.path.join(base_path, "vehicle-data.csv")
                            ^^^^^^^^^
NameError: name 'base_path' is not defined
[2025-01-24T23:04:48.443+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/finalassignment/tolldata/ETL_dag.py
[2025-01-24T23:04:48.462+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/finalassignment/tolldata/ETL_dag.py took 0.043 seconds
[2025-01-24T23:05:18.839+0000] {processor.py:186} INFO - Started process (PID=308) to work on /opt/airflow/dags/finalassignment/tolldata/ETL_dag.py
[2025-01-24T23:05:18.841+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/finalassignment/tolldata/ETL_dag.py for tasks to queue
[2025-01-24T23:05:18.844+0000] {logging_mixin.py:190} INFO - [2025-01-24T23:05:18.843+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/finalassignment/tolldata/ETL_dag.py
[2025-01-24T23:05:18.854+0000] {logging_mixin.py:190} INFO - [2025-01-24T23:05:18.849+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/finalassignment/tolldata/ETL_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/finalassignment/tolldata/ETL_dag.py", line 9, in <module>
    csv_file = os.path.join(base_path, "vehicle-data.csv")
                            ^^^^^^^^^
NameError: name 'base_path' is not defined
[2025-01-24T23:05:18.855+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/finalassignment/tolldata/ETL_dag.py
[2025-01-24T23:05:18.875+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/finalassignment/tolldata/ETL_dag.py took 0.042 seconds
[2025-01-24T23:05:49.407+0000] {processor.py:186} INFO - Started process (PID=378) to work on /opt/airflow/dags/finalassignment/tolldata/ETL_dag.py
[2025-01-24T23:05:49.409+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/finalassignment/tolldata/ETL_dag.py for tasks to queue
[2025-01-24T23:05:49.411+0000] {logging_mixin.py:190} INFO - [2025-01-24T23:05:49.410+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/finalassignment/tolldata/ETL_dag.py
[2025-01-24T23:05:49.419+0000] {logging_mixin.py:190} INFO - [2025-01-24T23:05:49.416+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/finalassignment/tolldata/ETL_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/finalassignment/tolldata/ETL_dag.py", line 9, in <module>
    csv_file = os.path.join(base_path, "vehicle-data.csv")
                            ^^^^^^^^^
NameError: name 'base_path' is not defined
[2025-01-24T23:05:49.420+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/finalassignment/tolldata/ETL_dag.py
[2025-01-24T23:05:49.436+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/finalassignment/tolldata/ETL_dag.py took 0.033 seconds
[2025-01-24T23:06:20.052+0000] {processor.py:186} INFO - Started process (PID=442) to work on /opt/airflow/dags/finalassignment/tolldata/ETL_dag.py
[2025-01-24T23:06:20.054+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/finalassignment/tolldata/ETL_dag.py for tasks to queue
[2025-01-24T23:06:20.057+0000] {logging_mixin.py:190} INFO - [2025-01-24T23:06:20.057+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/finalassignment/tolldata/ETL_dag.py
[2025-01-24T23:06:20.069+0000] {logging_mixin.py:190} INFO - [2025-01-24T23:06:20.067+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/finalassignment/tolldata/ETL_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/finalassignment/tolldata/ETL_dag.py", line 9, in <module>
    csv_file = os.path.join(base_path, "vehicle-data.csv")
                            ^^^^^^^^^
NameError: name 'base_path' is not defined
[2025-01-24T23:06:20.073+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/finalassignment/tolldata/ETL_dag.py
[2025-01-24T23:06:20.092+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/finalassignment/tolldata/ETL_dag.py took 0.048 seconds
[2025-01-24T23:06:50.944+0000] {processor.py:186} INFO - Started process (PID=506) to work on /opt/airflow/dags/finalassignment/tolldata/ETL_dag.py
[2025-01-24T23:06:50.947+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/finalassignment/tolldata/ETL_dag.py for tasks to queue
[2025-01-24T23:06:50.954+0000] {logging_mixin.py:190} INFO - [2025-01-24T23:06:50.953+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/finalassignment/tolldata/ETL_dag.py
[2025-01-24T23:06:50.962+0000] {logging_mixin.py:190} INFO - [2025-01-24T23:06:50.959+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/finalassignment/tolldata/ETL_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/finalassignment/tolldata/ETL_dag.py", line 9, in <module>
    csv_file = os.path.join(base_path, "vehicle-data.csv")
                            ^^^^^^^^^
NameError: name 'base_path' is not defined
[2025-01-24T23:06:50.964+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/finalassignment/tolldata/ETL_dag.py
[2025-01-24T23:06:50.987+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/finalassignment/tolldata/ETL_dag.py took 0.055 seconds
[2025-01-24T23:07:21.875+0000] {processor.py:186} INFO - Started process (PID=570) to work on /opt/airflow/dags/finalassignment/tolldata/ETL_dag.py
[2025-01-24T23:07:21.877+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/finalassignment/tolldata/ETL_dag.py for tasks to queue
[2025-01-24T23:07:21.884+0000] {logging_mixin.py:190} INFO - [2025-01-24T23:07:21.884+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/finalassignment/tolldata/ETL_dag.py
[2025-01-24T23:07:21.895+0000] {logging_mixin.py:190} INFO - [2025-01-24T23:07:21.890+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/finalassignment/tolldata/ETL_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/finalassignment/tolldata/ETL_dag.py", line 9, in <module>
    csv_file = os.path.join(base_path, "vehicle-data.csv")
                            ^^^^^^^^^
NameError: name 'base_path' is not defined
[2025-01-24T23:07:21.897+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/finalassignment/tolldata/ETL_dag.py
[2025-01-24T23:07:21.923+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/finalassignment/tolldata/ETL_dag.py took 0.057 seconds
[2025-01-24T23:07:52.200+0000] {processor.py:186} INFO - Started process (PID=634) to work on /opt/airflow/dags/finalassignment/tolldata/ETL_dag.py
[2025-01-24T23:07:52.204+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/finalassignment/tolldata/ETL_dag.py for tasks to queue
[2025-01-24T23:07:52.210+0000] {logging_mixin.py:190} INFO - [2025-01-24T23:07:52.209+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/finalassignment/tolldata/ETL_dag.py
[2025-01-24T23:07:52.222+0000] {logging_mixin.py:190} INFO - [2025-01-24T23:07:52.218+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/finalassignment/tolldata/ETL_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/finalassignment/tolldata/ETL_dag.py", line 9, in <module>
    csv_file = os.path.join(base_path, "vehicle-data.csv")
                            ^^^^^^^^^
NameError: name 'base_path' is not defined
[2025-01-24T23:07:52.223+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/finalassignment/tolldata/ETL_dag.py
[2025-01-24T23:07:52.264+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/finalassignment/tolldata/ETL_dag.py took 0.081 seconds
[2025-01-24T23:08:23.192+0000] {processor.py:186} INFO - Started process (PID=698) to work on /opt/airflow/dags/finalassignment/tolldata/ETL_dag.py
[2025-01-24T23:08:23.193+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/finalassignment/tolldata/ETL_dag.py for tasks to queue
[2025-01-24T23:08:23.196+0000] {logging_mixin.py:190} INFO - [2025-01-24T23:08:23.196+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/finalassignment/tolldata/ETL_dag.py
[2025-01-24T23:08:23.204+0000] {logging_mixin.py:190} INFO - [2025-01-24T23:08:23.202+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/finalassignment/tolldata/ETL_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/finalassignment/tolldata/ETL_dag.py", line 9, in <module>
    csv_file = os.path.join(base_path, "vehicle-data.csv")
                            ^^^^^^^^^
NameError: name 'base_path' is not defined
[2025-01-24T23:08:23.205+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/finalassignment/tolldata/ETL_dag.py
[2025-01-24T23:08:23.275+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/finalassignment/tolldata/ETL_dag.py took 0.095 seconds
